modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/FifthTundraG/HIJrax-Dragon-Egg-Mod/issues"
license = "GNU GPL 3.0"

[[mods]]
modId = "dragoneggmod"
version = "${version}"
displayName = "HIJrax's Dragon Egg Mod"
authors = "HIJrax, FifthTundraG"
description = '''
Makes the dragon egg more powerful, but it can no longer be hidden away forever...
'''
logoFile = "assets/dragoneggmod/icon.png"

[[dependencies.dragoneggmod]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dragoneggmod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "dragoneggmod.mixins.json"
